eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**